---
title: "Ontogenetic growth with DEB in R"
author: "James Maino"
date: "26 April 2017"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(deSolve)
library(ggplot2)
# library(shiny)
resV2<-data.frame(time=numeric(),res=numeric(),V=numeric())
```


```{r eruptions, echo=FALSE}
inputPanel(
  # initial vars
  sliderInput("V0", label = "V0: initial V, cm^3:",
              min = 0.0001, max = 0.2, value = 0.01),
  sliderInput("p_Am", label = "p_Am: assim. rate, J/cm^2/d:",
              min = 1, max = 10, value = 10, step = 0.1),
  sliderInput("E_G", label = "E_G: cost of growth, J/cm^3:",
              min = 1, max = 1000, value = 28, step = 1)
)
inputPanel(
  sliderInput("v", label = "v: conductance, cm/d:",
              min = 0.0001, max = 0.2, value = 0.02, step = 0.001),
  sliderInput("p_M", label = " p_M: maintenance rate, J/cm^3/d:",
              min = 0.0001, max = 20, value = 16, step = 0.2),
  sliderInput("f", label = "f: feeding response, -",
              min = 0, max = 1, value = 0.95, step = 0.01)
  
)

renderPlot({

# initial vars
V0 = input$V0 # intial structure, cm^3

# set parameters
p_Am =  input$p_Am  # SA specific assimilation rate, J/cm^2/d
E_G   = input$E_G   # cost of growth, J/cm^3
v     = input$v     # conductance, cm/d
p_M   = input$p_M   # vol. specific maintenance rate, J/cm^3/d
f     = input$f     # scaled functional response of feeding, -  
state <- c(res = f*p_Am/v*V0,
           V   = V0)

# solve time until 99% of ultimate length
L_inf = p_Am/p_M
L0<-V0^(1/3)
a<-1/(3/p_M/E_G + 3*L_inf/v)
t_inf<-1/a * log((L_inf-L0)/(L_inf-0.99*L_inf))

times <- seq(0,1000,length = 1000)

growth<-function(t, state, pars) {
  # parameters
  p_Am= pars[1]
  E_G = pars[2]
  v   = pars[3]
  p_M = pars[4]
  f   = pars[5]
  
  
  # state variables
  res = state[1]
  V   = state[2]
  
  # rate of change
  dres = f*p_Am*V^(2/3) - res* (E_G*v/V^(1/3) + p_M)/(res/V + E_G);
  dV   = (res*v/V^(1/3) - p_M*V)/(res/V + E_G);
  
  # return the rate of change
  list(c(dres, dV))
}


pars       <- c(p_Am  = p_Am,
                E_G   = E_G,
                v     = v,
                p_M   = p_M,
                f = f)
resV <- as.data.frame(ode(y = state, times = times, func = growth, parms = pars))


p<-ggplot()+
  geom_line(data=resV, aes(time,V))+
  geom_line(data=resV2,aes(time,V), color = 'red', alpha = 0.5)+
  ylim(0,1)+
  xlim(0,1000)+
  theme_classic()
print(p)
resV2<<-resV
})
```

